# ASP.NET Core - CI/CD
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  WebAppName: 'webSiteienua2xiqn3ye'

steps:
# Restore dependencies
- task: NuGetToolInstaller@0
  displayName: 'Acquire NuGet'
  inputs:
    versionSpec: 4.4.1
    
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '**\*.sln'

# Build your project and publish artifacts
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)\\"'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
   
# Run your tests
- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'


# -------- CD --------
# https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp
# https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure
# Task         : Azure App Service Deploy
- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: webSiteienua2xiqn3ye'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    WebAppName: '$(WebAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# Task         : Index Sources & Publish Symbols
- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

# Task         : Publish Build Artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()
