# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# https://github.com/Microsoft/azure-pipelines-yaml/blob/master/templates/asp.net-core.yml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
# ------------------------ DMR-Azure Web App for ASP.NET-CI ------------------------
# Below copied from Azure DevOps generated CI; were no warnings in designer
# ----------------------------------------------------------------------------------
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
